export { default as PeopleList } from './PeopleList/PeopleList'
export { default as ErrorMessage } from './ErrorMessage/ErrorMessage'
export { default as Layout } from './Layout/Layout'
export { default as Header } from './Header/Header'
export { default as PeopleNavigation } from './PeopleNavigation/PeopleNavigation'
export { default as UiButton } from './UI/UiButton/UiButton'
